# Generated by Django 3.2.5 on 2021-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20210727_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(default='', max_length=256),
        ),
    ]
