# Generated by Django 3.2.5 on 2021-07-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20210728_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='images/placeholder.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(default='images/placeholder.jpeg', upload_to='images/'),
        ),
    ]
