# Generated by Django 3.2.5 on 2021-07-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_auto_20210728_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='showcase.series'),
        ),
    ]
